services:
  web:
    build: .
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: localhost
      DB_PORT: "${DB_PORT}:3306"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
